plugin:
  name: "GPIrrigation"
  author: "Florent Boutin"
  description: "Module de control pour les systèmes d'irrigation de GreenPi"
  uid: "GPIrrigation"
  migration: false

actions:
  - name: "start irrigation"
    fields:
      - "Sensor UID"
  - name: "stop irrigation"
    fields:
      - "Sensor UID"